# Generated by Django 4.1.6 on 2023-04-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupPredictor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, db_column='Organization Name', max_length=200, null=True)),
                ('last_funding_amount_currency_in_usd_field', models.DecimalField(blank=True, db_column='Last Funding Amount Currency (in USD)', decimal_places=65535, max_digits=65535, null=True)),
                ('industries', models.CharField(blank=True, db_column='Industries', max_length=200, null=True)),
                ('headquarters_location', models.CharField(blank=True, db_column='Headquarters Location', max_length=200, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('founded_date', models.DateField(blank=True, db_column='Founded Date', null=True)),
                ('estimated_revenue_range', models.CharField(blank=True, db_column='Estimated Revenue Range', max_length=200, null=True)),
                ('website', models.CharField(blank=True, db_column='Website', max_length=200, null=True)),
                ('founders', models.CharField(blank=True, db_column='Founders', max_length=500, null=True)),
                ('number_of_funding_rounds', models.FloatField(blank=True, db_column='Number of Funding Rounds', null=True)),
                ('funding_status', models.CharField(blank=True, db_column='Funding Status', max_length=200, null=True)),
                ('last_funding_type', models.CharField(blank=True, db_column='Last Funding Type', max_length=200, null=True)),
                ('last_equity_funding_amount_currency_in_usd_field', models.DecimalField(blank=True, db_column='Last Equity Funding Amount Currency (in USD)', decimal_places=65535, max_digits=65535, null=True)),
                ('last_equity_funding_type', models.CharField(blank=True, db_column='Last Equity Funding Type', max_length=200, null=True)),
                ('total_equity_funding_amount_currency_in_usd_field', models.DecimalField(blank=True, db_column='Total Equity Funding Amount Currency (in USD)', decimal_places=65535, max_digits=65535, null=True)),
                ('total_funding_amount_currency_in_usd_field', models.DecimalField(blank=True, db_column='Total Funding Amount Currency (in USD)', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
